<a href="https://colab.research.google.com/github/JakeOh/202006_iw_pyda_wkd/blob/master/py08_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# NumPy: Numerical Python
# 다차원 배열(array) 빠르게 조작, 계산

import numpy as np
# import: numpy 라이브러리 기능을 불러와서 사용
# as: 별명

np.__version__

'1.18.5'

In [5]:
# Python list(리스트): 여러개의 데이터를 저장할 수 있는 자료 타입.
num_list = [1, 2, 3]
print(type(num_list), num_list)

# numpy array(배열): 한가지 타입의 데이터 여러개를 저장할 수 있는 자료 타입
num_array = np.array([1, 2, 3])
print(type(num_array))  # ndarray: n-dimensional array
print(num_array)

<class 'list'> [1, 2, 3]
<class 'numpy.ndarray'>
[1 2 3]


In [10]:
# Python 리스트는 다른 타입의 값들도 함께 저장할 수 있음.
list1 = [1, 'abc', True]
print(list1)  # 숫자, 문자열, 논리 타입을 함께 저장

# numpy ndarray는 한가지 타입의 값들만 저장할 수 있음.
array1 = np.array([1, 'abc', True])
print(array1)  # 숫자 1과 논리 타입 True가 문자열로 변환되서 저장.
print(array1.dtype)  # Unicode 타입 - 문자열

[1, 'abc', True]
['1' 'abc' 'True']
<U21


In [14]:
# Python 리스트는 + 연산과 * 연산을 사용할 수 있음.
# Python 리스트는 -, /, %, // 등의 연산은 제공하지 않음.
list1 = [1, 2, 3]
list2 = [4, 5, 6]
print(list1 + list2)  # 두 개의 리스트를 이어서 붙여줌.
print(list1 * 3)  # 곱한 숫자만큼 원소들을 반복해서 리스트의 크기를 늘림.

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [17]:
# numpy ndarray는 모든 산술 연산(+, -, *, /, %, //)을 제공.
# 같은 위치의 원소들끼리 산술 연산을 수행함.
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(array1.dtype)  # int64 - 정수
print(array1 + array2)
print(array1 - array2)

int64
[5 7 9]
[-3 -3 -3]


In [19]:
# ndarray를 만들어주는 함수들
array3 = np.array([1, 2, 3, 4, 5])
print(array3)

array4 = np.arange(1, 6)  # array with range
# start <= x < end, 1씩 증가하는 숫자로 이루어진 배열
print(array4)

[1 2 3 4 5]
[1 2 3 4 5]


In [22]:
array5 = np.ones(5, dtype=np.int)
print(array5)
print(array5.shape)  # 1차원 배열(array), 원소 개수=5
print(array5.dtype)

[1 1 1 1 1]
(5,)
int64


In [24]:
array6 = np.ones((2, 3))
print(array6)
print(array6.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [27]:
array7 = np.zeros((3, 4))  # shape(row, column)
print(array7)
print(array7.shape)
print(len(array7))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
3


In [30]:
array8 = np.eye(3)
# 항등 행렬을 만들어주는 함수
# 항등 행렬: 대각선의 원소들은 모두 1이고, 나머지는 0으로 채워진 정사각행렬.
print(array8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
# 난수(random number)로 배열을 만들어 주는 함수들
array9 = np.random.rand(3)  # 0 <= r < 1 난수를 생성
print(array9, array9.shape)

array10 = np.random.rand(2, 3)
print(array10, array10.shape)

[0.22748188 0.3485895  0.21248074] (3,)
[[0.3192828  0.42269486 0.96759311]
 [0.62628459 0.45995019 0.402069  ]] (2, 3)


In [36]:
array11 = np.random.randn(2, 3)
# noraml distribution(정규 분포)을 따르는 난수를 생성
# 정규 분포: 평균이 0이고, 표준편차가 1인 분포
print(array11)

[[ 0.21161775 -2.18859181  1.07846034]
 [-0.64798258 -0.13864995 -1.77978211]]


In [38]:
array12 = np.random.randint(1, 7, size=(3, 4))
# low <= r < high의 정수들로 이루어진 난수
print(array12)

[[6 4 6 5]
 [1 5 5 2]
 [2 2 6 3]]


In [39]:
np.random.random_integers(1, 7, size=(3, 4))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 7 + 1) instead
  """Entry point for launching an IPython kernel.


array([[1, 2, 2, 7],
       [4, 5, 7, 6],
       [6, 5, 7, 1]])

In [40]:
# NumPy 인덱스, 인덱싱(인덱스를 이용해서 원소를 선택)
array = np.random.rand(10)
print(array)  # 1-D array

[0.92532804 0.8904268  0.69859424 0.56246638 0.9590777  0.81703843
 0.44232698 0.48427587 0.58849572 0.76620099]


In [49]:
print(array[9])
print(array[1:4])  # start <= i < end 범위 인덱스
print(array[:4])  # 시작 인덱스를 생략하면 기본값은 0
print(array[8:])  # 마지막 인덱스를 생략하면 기본값은 array의 끝까지
print(array[:])
print(array[-2:])

0.766200994129551
[0.8904268  0.69859424 0.56246638]
[0.92532804 0.8904268  0.69859424 0.56246638]
[0.58849572 0.76620099]
[0.92532804 0.8904268  0.69859424 0.56246638 0.9590777  0.81703843
 0.44232698 0.48427587 0.58849572 0.76620099]
[0.58849572 0.76620099]


In [50]:
array = np.random.rand(3, 4)
print(array)  # (3, 4) 2-D array

[[0.25295429 0.67359116 0.12517554 0.10030374]
 [0.01656498 0.633541   0.5459743  0.05414289]
 [0.7423642  0.35223791 0.19420794 0.42129164]]


In [55]:
print(array[0, 0])  # [row index, column index]
print(array[1:3, 2:4])
print(array[:, 2:4])

0.25295428841415146
[[0.5459743  0.05414289]
 [0.19420794 0.42129164]]
[[0.12517554 0.10030374]
 [0.5459743  0.05414289]
 [0.19420794 0.42129164]]


In [57]:
# NumPy array의 인덱싱을 할 때 row 또는 column 인덱스를 
# 숫자 1개만 준 경우, 2-D 배열이 1-D 배열로 바뀜!
print(array[:, 0])  # (3,) 1-D array
print(array[0, :])  # (4,) 1-D array

[0.25295429 0.01656498 0.7423642 ]
[0.25295429 0.67359116 0.12517554 0.10030374]


In [59]:
# NumPy array에서 인덱싱을 할 때, 인덱스에 배열을 줄 수 있음.
print(array[:, [0, 3]])
print(array[:, [0]])  # (3, 1) 2-D array

[[0.25295429 0.10030374]
 [0.01656498 0.05414289]
 [0.7423642  0.42129164]]
[[0.25295429]
 [0.01656498]
 [0.7423642 ]]


In [61]:
# boolean indexing: 논리값(True/False)들을 사용해서 필요한 원소들을 선택
array = np.random.randn(10)
print(array)

[ 1.47905334  0.1631968   1.56897232 -1.0214501   0.37287218  0.26237782
  0.43880213  0.71487526 -0.38843071 -1.20445211]


In [62]:
array > 0

array([ True,  True,  True, False,  True,  True,  True,  True, False,
       False])

In [63]:
print(array[array > 0])

[1.47905334 0.1631968  1.56897232 0.37287218 0.26237782 0.43880213
 0.71487526]


In [65]:
# boolean indexing을 할 때 &, |, ~ 연산자를 함께 사용할 수 있음.
# 2개의 조건을 & 또는 |로 연결할 때는 반드시 ()를 사용해야 함.
print(array[(array > 0.5) | (array < -0.5)])
print(array[(array < 0.5) & (array > -0.5)])

[ 1.47905334  1.56897232 -1.0214501   0.71487526 -1.20445211]
[ 0.1631968   0.37287218  0.26237782  0.43880213 -0.38843071]


In [69]:
np.random.seed(1)  # 난수를 생성하는 결과를 재현할 수 있도록.
array = np.random.randn(3, 3)
print(array)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]]


In [70]:
print(array > 0)

[[ True False False]
 [False  True False]
 [ True False  True]]


In [71]:
print(array[array > 0])
# 결과가 1-D array

[1.62434536 0.86540763 1.74481176 0.3190391 ]


In [77]:
print(array[[0, 2]])
print(array[[0, 2],])
print(array[[0, 2], :])
# 위의 세가지 인덱싱 방식은 같은 결과!

[[ 1.62434536 -0.61175641 -0.52817175]
 [ 1.74481176 -0.7612069   0.3190391 ]]
[[ 1.62434536 -0.61175641 -0.52817175]
 [ 1.74481176 -0.7612069   0.3190391 ]]
[[ 1.62434536 -0.61175641 -0.52817175]
 [ 1.74481176 -0.7612069   0.3190391 ]]


In [78]:
print(array[[True, False, True]])

[[ 1.62434536 -0.61175641 -0.52817175]
 [ 1.74481176 -0.7612069   0.3190391 ]]


In [82]:
X = np.arange(16).reshape((4, 4))
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [85]:
y = np.array([0, 0, 1, 1])
print(y)
print(y == 0)

[0 0 1 1]
[ True  True False False]


In [84]:
print(X[y == 0])

[[0 1 2 3]
 [4 5 6 7]]
